### ISSUE TITLE
Split out raw data from this repo

### ISSUE THREAD

**Issue by dmcconachie** [UM-ARM-Lab/kinect2_calibration_files#1]
People should not need to download the raw jpgs that were used in calibration just to get the launch and final calibrations files. So either these files should move elsewhere, or the raw calibration data should be moved elsewhere (and purged from the git history).

**Comment by dmcconachie** [comment]
A good place for this would likely be the NAS, with some sort of a link embedded in this repo.

**Comment by dmcconachie** [comment]
@a-price Thoughts?

**Comment by a-price** [comment]
Either the NAS or somewhere with git LFS.

**Comment by dmcconachie** [comment]
Files are now on the NAS in the `kinect2_calibration_data` folder.
